---
- name: Setup Flask Application Environment
  hosts: local
  become: yes
  vars:
    app_dir: "{{ ansible_env.HOME }}/devops-app"
    venv_dir: "{{ ansible_env.HOME }}/devops-app/venv"

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
      when: ansible_os_family == "Debian"

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"

    - name: Create Python virtual environment
      command: python3 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"
      when: ansible_os_family == "Debian"
