name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps: # <<< The list of steps starts here
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Start of Added Debugging ---   <<< NEW STEP ADDED HERE
      - name: List files before linting (DEBUG)
        run: |
          echo "Current directory before flake8:"
          pwd
          echo "Listing files:"
          ls -la
      # --- End of Added Debugging ---
      # Step 4: Lint with flake8  <<< This step is now AFTER the debug step
      - name: Lint with flake8
        run: |
          flake8 app.py test_app.py --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run the unit tests
      - name: Test with pytest
        run: |
          pytest
