name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from GitHub into the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Python version we want
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Step 3: Install all needed Python packages from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Check code style with flake8
      - name: Lint with flake8
        run: |
          flake8 app.py test_app.py --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run the unit tests
      - name: Test with pytest
        run: |
          pytest
