name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Start of Added Debugging ---   <<< IS THIS BLOCK PRESENT?
      - name: List files before linting (DEBUG)
        run: |
          echo "Current directory before flake8:"
          pwd
          echo "Listing files:"
          ls -la
      # --- End of Added Debugging ---
      - name: Lint with flake8 # <<< IS 'pip install flake8' REMOVED FROM HERE?
        run: |
          flake8 app.py test_app.py --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest
